version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: docker/php.Dockerfile
    volumes:
      - .:/var/www/app
    user: "${UID}:${GID}"
    depends_on:
      - db
      - redis
    environment:
      DATABASE_URL: "mysql://app:app@db:3306/app?charset=utf8mb4"
      REDIS_URL: "redis://redis:6379"

  nginx:
    image: nginx:alpine
    volumes:
      - .:/var/www/app
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "8081:80"  # Important to have the same as within DEFAULT_URI
    depends_on:
      - app

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3350:3306"
    volumes:
      - db_data:/var/lib/mysql

  redis:
    image: redis:7-alpine
    restart: always

#  kafka:
#    image: bitnami/kafka:3
#    environment:
#      - KAFKA_CFG_NODE_ID=0
#      - KAFKA_CFG_PROCESS_ROLES=broker,controller
#      - KAFKA_CFG_CONTROLLER_QUORUM_VOTERS=0@kafka:9093
#      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
#      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
#      - KAFKA_CFG_CONTROLLER_LISTENER_NAMES=CONTROLLER
#    ports:
#      - "9092:9092"

volumes:
  db_data:
