name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-test:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: "mysql://root:root@127.0.0.1:3306/test_db?serverVersion=8.0&charset=utf8mb4"

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: test_db
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, pdo, pdo_mysql
          coverage: none

      - name: Install dependencies
        run: composer install --no-interaction --no-progress --prefer-dist --ignore-platform-req=ext-rdkafka

      - name: Setup environment
        run: |
          cp .env.test .env.test.local
          php bin/console doctrine:database:create --env=test --if-not-exists
          php bin/console doctrine:migrations:migrate --env=test --no-interaction

      - name: Run PHPStan
        run: vendor/bin/phpstan analyse --no-progress --memory-limit=2048M

      - name: Run PHPUnit
        run: vendor/bin/phpunit --colors=always
